const roommates = [
  {
    id: 1,
    name: "Chiamaka Okafor",
    image: "https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=400",
    isOnline: true,
    university: "Yaba",
    location: "Lagos State",
    price: "₦70,000/yr",
    tags: ["Football addict", "Night reader", "Social"],
    gender: "Female",
    roomType: "Shared room",
    distance: 0.8,
    aboutMe: "Hi! I'm Chiamaka, a 300-level student who loves calm and organized spaces. I enjoy watching K-dramas, cooking light meals, and I'm generally an early sleeper. I'm tidy and respectful of people's privacy, so I'd prefer a roommate who shares similar habits.",
    interests: ["Watching K-dramas", "Cooking", "Reading romance novels", "Weekend hangouts", "church choir rehearsals"],
    apartmentPreference: {
      type: "Shared 2-bedroom flat",
      location: "UNILAG - Akoka / Bariga",
      price: "₦70,000",
      tags: ["Constant light in area", "running water", "close to campus"],
    },
    preferences: {
      smoking: "Non-smoker",
      social: "Introvert",
      pets: "No Pets",
      lifestyle: "Clean",
      guests: "Not okay",
      music: "Likes quiet",
      food: "Foodie",
      sleep: "Early Bird",
    }
  },
  {
    id: 2,
    name: "Kunle Oladipo",
    image: "https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=400",
    isOnline: true,
    university: "UNIBEN",
    location: "Ugbowo",
    price: "₦100,000/yr",
    tags: ["Party lover", "Basketball fan", "Outgoing"],
    gender: "Male",
    roomType: "Self-contained",
    distance: 2.5,
    aboutMe: "Hey, I'm Kunle. I'm pretty outgoing and love a good time. I study engineering, play basketball on weekends, and I'm looking for a roommate who is chill, doesn't mind having a few friends over, and is clean in the common areas.",
    interests: ["Basketball", "Video Games", "Movies", "Hanging with friends"],
    apartmentPreference: {
      type: "Self-contained",
      location: "UNIBEN - BDPA",
      price: "₦120,000",
      tags: ["Good security", "close to campus"],
    },
    preferences: {
      smoking: "Non-smoker",
      social: "Extrovert",
      pets: "No Pets",
      lifestyle: "A bit messy",
      guests: "Okay",
      music: "Likes music",
      food: "Orders out",
      sleep: "Night Owl",
    }
  },
  {
    id: 3,
    name: "Aisha Bello",
    image: "https://images.pexels.com/photos/1181690/pexels-photo-1181690.jpeg?auto=compress&cs=tinysrgb&w=400",
    isOnline: false,
    university: "LASU",
    location: "Ojo / Iba",
    price: "₦85,000/yr",
    tags: ["Gym rat", "Music lover", "Easygoing"],
    gender: "Female",
    roomType: "1-bedroom apartment",
    distance: 4.0,
    aboutMe: "Aisha here! I'm in my final year. I'm at the gym most days, and when I'm not, I'm probably listening to music and studying. Looking for a female roommate who is focused, clean, and respectful.",
    interests: ["Fitness", "Afrobeats", "Reading", "Fashion"],
    apartmentPreference: {
      type: "1-bedroom apartment",
      location: "LASU - Iba",
      price: "₦90,000",
      tags: ["running water", "Good security"],
    },
    preferences: {
      smoking: "Non-smoker",
      social: "Introvert",
      pets: "No Pets",
      lifestyle: "Clean",
      guests: "Not okay",
      music: "Likes music",
      food: "Loves cooking",
      sleep: "Early Bird",
    }
  },
  {
    id: 4,
    name: "Musa Abdullahi",
    image: "https://images.pexels.com/photos/3775540/pexels-photo-3775540.jpeg?auto=compress&cs=tinysrgb&w=400",
    isOnline: true,
    university: "BUK",
    location: "Kano",
    price: "₦95,000/yr",
    tags: ["Football addict", "Night reader", "Social"],
    gender: "Male",
    roomType: "Shared room",
    distance: 6.0,
    aboutMe: "My name is Musa. I'm a postgraduate student. I'm a big football fan (Man United!). I'm generally quiet and spend most nights studying, but I'm friendly and always up for a good conversation. I value a clean and quiet living space.",
    interests: ["Football", "History documentaries", "Chess"],
    apartmentPreference: {
      type: "Shared room",
      location: "BUK - New Campus",
      price: "₦100,000",
      tags: ["Stable power", "Good water supply"],
    },
    preferences: {
      smoking: "Non-smoker",
      social: "Introvert",
      pets: "No Pets",
      lifestyle: "Clean",
      guests: "Not okay",
      music: "Likes quiet",
      food: "Loves cooking",
      sleep: "Night Owl",
    }
  },
  {
    id: 5,
    name: "Ngozi Okeke",
    image: "https://images.pexels.com/photos/3778212/pexels-photo-3778212.jpeg?auto=compress&cs=tinysrgb&w=400",
    isOnline: false,
    university: "UNIPORT",
    location: "Choba",
    price: "₦70,000/yr",
    tags: ["Artist", "Nature lover", "Creative"],
    gender: "Female",
    roomType: "2-bedroom apartment",
    distance: 1.5,
    aboutMe: "Creative soul and art student. I love painting, visiting parks, and quiet mornings. I'm looking for a roommate who is also creative, tidy, and enjoys a peaceful home environment. I'm an early bird and a non-smoker.",
    interests: ["Painting", "Hiking", "Thrift shopping", "Gardening"],
    apartmentPreference: {
      type: "2-bedroom apartment",
      location: "UNIPORT - Abuja Park",
      price: "₦80,000",
      tags: ["Good ventilation", "Art-friendly space"],
    },
    preferences: {
      smoking: "Non-smoker",
      social: "Introvert",
      pets: "Okay with pets",
      lifestyle: "Clean",
      guests: "Not okay",
      music: "Likes quiet",
      food: "Foodie",
      sleep: "Early Bird",
    }
  },
  {
    id: 6,
    name: "Daniel Eze",
    image: "https://images.pexels.com/photos/1587009/pexels-photo-1587009.jpeg?auto=compress&cs=tinysrgb&w=400",
    isOnline: true,
    university: "Yaba",
    location: "Lagos State",
    price: "₦110,000/yr",
    tags: ["Tech bro", "Gamer", "Easygoing"],
    gender: "Male",
    roomType: "Self-contained",
    distance: 3.2,
    aboutMe: "I'm a computer science student. Most of my time is spent coding or gaming. I'm a night owl but I'm considerate with noise. Looking for a roommate who is independent, minds their business, and pays bills on time.",
    interests: ["Coding", "Gaming (Valorant)", "Sci-fi movies"],
    apartmentPreference: {
      type: "Self-contained",
      location: "Yaba - Tejuosho",
      price: "₦150,000",
      tags: ["Fast internet", "Stable power"],
    },
    preferences: {
      smoking: "Non-smoker",
      social: "Introvert",
      pets: "No Pets",
      lifestyle: "A bit messy",
      guests: "Okay",
      music: "Likes music",
      food: "Orders out",
      sleep: "Night Owl",
    }
  },
  {
    id: 7,
    name: "Chidera Nwankwo",
    image: "https://images.pexels.com/photos/846741/pexels-photo-846741.jpeg?auto=compress&cs=tinysrgb&w=400",
    isOnline: false,
    university: "UNN",
    location: "Nsukka",
    price: "₦75,000/yr",
    tags: ["Social", "Loves cooking", "Friendly"],
    gender: "Male",
    roomType: "Shared room",
    distance: 0.5,
    aboutMe: "Hey! I'm a friendly and social person who loves to cook for others. I'm studying mass communication. I'm looking for a clean and friendly roommate to share a space with. I'm okay with having friends over occasionally.",
    interests: ["Cooking", "Socializing", "Volunteering", "Podcasts"],
    apartmentPreference: {
      type: "Shared room",
      location: "UNN - Hilltop",
      price: "₦80,000",
      tags: ["Good kitchen", "Close to school"],
    },
    preferences: {
      smoking: "Non-smoker",
      social: "Extrovert",
      pets: "No Pets",
      lifestyle: "Clean",
      guests: "Okay",
      music: "Likes music",
      food: "Loves cooking",
      sleep: "Early Bird",
    }
  },
  {
    id: 8,
    name: "Joshua Adekunle",
    image: "https://images.pexels.com/photos/3760327/pexels-photo-3760327.jpeg?auto=compress&cs=tinysrgb&w=400",
    isOnline: true,
    university: "Bayero University",
    location: "Kano",
    price: "₦90,000/yr",
    tags: ["Fun to be around", "Loves fashion", "Gamer"],
    gender: "Male",
    roomType: "1-bedroom apartment",
    distance: 10.0,
    aboutMe: "I'm Joshua, a business admin student. I'm into fashion and gaming. I'm pretty laid back and easy to live with. I respect personal space but I'm also down to hang out. Looking for someone similar.",
    interests: ["Fashion", "Gaming (FIFA)", "Photography"],
    apartmentPreference: {
      type: "1-bedroom apartment",
      location: "BUK - Old Campus",
      price: "₦100,000",
      tags: ["Modern apartment", "Good security"],
    },
    preferences: {
      smoking: "Smoker",
      social: "Extrovert",
      pets: "No Pets",
      lifestyle: "A bit messy",
      guests: "Okay",
      music: "Likes music",
      food: "Foodie",
      sleep: "Night Owl",
    }
  },
  {
    id: 9,
    name: "Chioma Okoro",
    image: "https://images.pexels.com/photos/2787341/pexels-photo-2787341.jpeg?auto=compress&cs=tinysrgb&w=400",
    isOnline: false,
    university: "Yaba",
    location: "Lagos State",
    price: "₦80,000/yr",
    tags: ["Bookworm", "Quiet", "Clean"],
    gender: "Female",
    roomType: "Shared room",
    distance: 2.1,
    aboutMe: "Hello, I'm Chioma. I'm a law student, so I spend a lot of time reading and studying. I'm looking for a quiet, clean, and serious-minded female roommate. My ideal space is peaceful and orderly. I'm a very early bird and a non-smoker.",
    interests: ["Reading", "Classical music", "Debating", "Museums"],
    apartmentPreference: {
      type: "Shared room",
      location: "Yaba - Akoka",
      price: "₦80,000",
      tags: ["Quiet neighborhood", "Stable power"],
    },
    preferences: {
      smoking: "Non-smoker",
      social: "Introvert",
      pets: "No Pets",
      lifestyle: "Clean",
      guests: "Not okay",
      music: "Likes quiet",
      food: "Loves cooking",
      sleep: "Early Bird",
    }
  },
];

export default roommates;