const roommates = [
  {
    id: 1,
    name: "Chiamaka Okafor",
    image: "https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=400",
    university: "Yaba",
    location: "Lagos State",
    price: "₦70,000/yr",
    tags: ["Football addict", "Night reader", "Social"],
    gender: "Female",
    roomType: "Shared room",
    distance: 0.8,
  },
  {
    id: 2,
    name: "Kunle Oladipo",
    image: "https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=400",
    university: "UNIBEN",
    location: "Ugbowo",
    price: "₦100,000/yr",
    tags: ["Party lover", "Basketball fan", "Outgoing"],
    gender: "Male",
    roomType: "Self-contained",
    distance: 2.5,
  },
  {
    id: 3,
    name: "Aisha Bello",
    image: "https://images.pexels.com/photos/1181690/pexels-photo-1181690.jpeg?auto=compress&cs=tinysrgb&w=400",
    university: "LASU",
    location: "Ojo / Iba",
    price: "₦85,000/yr",
    tags: ["Gym rat", "Music lover", "Easygoing"],
    gender: "Female",
    roomType: "1-bedroom apartment",
    distance: 4.0,
  },
  {
    id: 4,
    name: "Musa Abdullahi",
    image: "https://images.pexels.com/photos/3775540/pexels-photo-3775540.jpeg?auto=compress&cs=tinysrgb&w=400",
    university: "BUK",
    location: "Kano",
    price: "₦95,000/yr",
    tags: ["Football addict", "Night reader", "Social"],
    gender: "Male",
    roomType: "Shared room",
    distance: 6.0,
  },
  {
    id: 5,
    name: "Ngozi Okeke",
    image: "https://images.pexels.com/photos/3778212/pexels-photo-3778212.jpeg?auto=compress&cs=tinysrgb&w=400",
    university: "UNIPORT",
    location: "Choba",
    price: "₦70,000/yr",
    tags: ["Football addict", "Night reader", "Social"],
    gender: "Female",
    roomType: "2-bedroom apartment",
    distance: 1.5,
  },
  {
    id: 6,
    name: "Daniel Eze",
    image: "https://images.pexels.com/photos/1587009/pexels-photo-1587009.jpeg?auto=compress&cs=tinysrgb&w=400",
    university: "Yaba",
    location: "Lagos State",
    price: "₦110,000/yr",
    tags: ["Gym rat", "Music lover", "Easygoing"],
    gender: "Male",
    roomType: "Self-contained",
    distance: 3.2,
  },
  {
    id: 7,
    name: "Chidera Nwankwo",
    image: "https://images.pexels.com/photos/846741/pexels-photo-846741.jpeg?auto=compress&cs=tinysrgb&w=400",
    university: "UNN",
    location: "Nsukka",
    price: "₦75,000/yr",
    tags: ["Social", "Loves cooking", "Friendly"],
    gender: "Male",
    roomType: "Shared room",
    distance: 0.5,
  },
  {
    id: 8,
    name: "Joshua Adekunle",
    image: "https://images.pexels.com/photos/3760327/pexels-photo-3760327.jpeg?auto=compress&cs=tinysrgb&w=400",
    university: "Bayero University",
    location: "Kano",
    price: "₦90,000/yr",
    tags: ["Fun to be around", "Loves fashion", "Gamer"],
    gender: "Male",
    roomType: "1-bedroom apartment",
    distance: 10.0,
  },
  {
    id: 9,
    name: "Chioma Okoro",
    image: "https://images.pexels.com/photos/2787341/pexels-photo-2787341.jpeg?auto=compress&cs=tinysrgb&w=400",
    university: "Yaba",
    location: "Lagos State",
    price: "₦80,000/yr",
    tags: ["Football addict", "Night reader", "Social"],
    gender: "Female",
    roomType: "Shared room",
    distance: 2.1,
  },
];

export default roommates;